config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'tops#index'
  resources :incomes, only: [:new, :create, :destroy] do
    collection do
      get 'search'
    end
  end
  resources :fixed_costs, only: [:new, :create, :destroy] do
    collection do
      get 'search'
    end
  end
  resources :variable_costs, only: [:new, :create, :destroy]  do
    collection do
      get 'search'
    end
  end
  resources :purchase_plans, only: [:index, :new, :create, :destroy]
  resources :budgets, only: [:index, :new, :create, :edit, :update]
end

app/models/budget.rb
class Budget < ApplicationRecord
  belongs_to :user

  with_options presence: true, numericality: { only_integer: true, less_than: 10_000_001, message: 'は半角数字で 0円 以上  1,000,000 円 以内で入力してください' } do
    validates :house
    validates :communications
    validates :electricity
    validates :gas
    validates :water
    validates :education
    validates :premium
    validates :lawn
    validates :fixed_etcetera
    validates :food
    validates :commodity
    validates :transportation
    validates :hobby
    validates :clothes
    validates :health
    validates :culture
    validates :book
    validates :cafe
    validates :social
    validates :special
    validates :variable_etcetera
  end
end

app/controllers/budgets_controller.rb
class BudgetsController < ApplicationController
  def index
    user = User.find(current_user.id)
    this_month = Date.today.beginning_of_month..Date.today.end_of_month
    @fixed_cost = user.fixed_costs.where(expense_date: this_month)
    @variable_cost = user.variable_costs.where(expense_date: this_month)
    @fixed_cost_month = user.fixed_costs.where(expense_date: this_month).sum(:price)
    @variable_cost_month = user.variable_costs.where(expense_date: this_month).sum(:price)
    # 予算登録済みユーザーにのみ予算を表示
    budget_present
  end

  # 予算登録済みログインユーザーが直接URLを入力して予算登録ページに遷移しようとするとトップページに遷移
  def new
    user = User.find(current_user.id)
    if user.budget.present?
      redirect_to root_path
    else
      @budget = Budget.new
    end
  end

  def create
    @budget = Budget.new(budget_params)
    if @budget.save
      redirect_to budgets_path
    else
      render 'new'
    end
  end

  # 予算登録していないログインユーザーが直接URLを入力して他ユーザーの予算編集ページに遷移しようとするとトップページに遷移
  def edit
    user = User.find(current_user.id)
    @budget = Budget.find(params[:id])
    redirect_to root_path unless current_user.id == @budget.user_id && user.budget.present?
  end

  def update
    @budget = Budget.find(params[:id])
    if @budget.update(budget_params)
      redirect_to budgets_path
    else
      render 'edit'
    end
  end

  private

  def budget_params
    params.require(:budget).permit(:house, :communications, :electricity, :gas, :water, :education, :premium, :lawn, :fixed_etcetera, :food, :commodity, :transportation, :hobby, :clothes, :health, :culture, :book, :cafe, :social, :special, :variable_etcetera).merge(user_id: current_user.id)
  end

  # 固定費予算の合計値と変動費予算の合計値を算出
  def budget_present
    user = User.find(current_user.id)
    if user.budget.present?
      @budget = user.budget
      @fixed_budget = (@budget.house + @budget.communications + @budget.electricity + @budget.gas + @budget.water + @budget.education + @budget.premium + @budget.lawn + @budget.fixed_etcetera)
      @variable_budget = (@budget.food + @budget.commodity + @budget.transportation + @budget.hobby + @budget.clothes + @budget.health + @budget.culture + @budget.book + @budget.cafe + @budget.social + @budget.special + @budget.variable_etcetera)
    end
  end
end

app/helpers/budgets_helper.rb
module BudgetsHelper
end

app/views/budgets/_blank.html.erb
<div class="budget orange-color">
  <div class="category-budget fas fa-money-bill-wave"> 固定費</div>
  <div class="month-budget"><b> 円</b></div>
  <div class="month-expense"><%= @fixed_cost_month.to_s(:delimited)%><b> 円</b></div>
  <div class="month-balance"><b> 円</b></div>
</div>
<div class="budget odd-color">
  <div class="category-budget fas fa-house-user"> 住居費</div>
  <div class="month-budget"><b> 円</b></div>
  <div class="month-expense"><%= @fixed_cost.where(fixed_cost_category_id: 2).sum(:price).to_s(:delimited)%><b> 円</b></div>
  <div class="month-balance"><b> 円</b></div>
</div>
<div class="budget even-color">
  <div class="category-budget fas fa-broadcast-tower"> 通信費</div>
  <div class="month-budget"><b> 円</b></div>
  <div class="month-expense"><%= @fixed_cost.where(fixed_cost_category_id: 3).sum(:price).to_s(:delimited)%><b> 円</b></div>
  <div class="month-balance"><b> 円</b></div>
</div>
<div class="budget odd-color">
  <div class="category-budget fas fa-lightbulb"> 電気代</div>
  <div class="month-budget"><b> 円</b></div>
  <div class="month-expense"><%= @fixed_cost.where(fixed_cost_category_id: 4).sum(:price).to_s(:delimited)%><b> 円</b></div>
  <div class="month-balance"><b> 円</b></div>
</div>
<div class="budget even-color">
  <div class="category-budget fas fa-fire-alt"> ガス代</div>
  <div class="month-budget"><b> 円</b></div>
  <div class="month-expense"><%= @fixed_cost.where(fixed_cost_category_id: 5).sum(:price).to_s(:delimited)%><b> 円</b></div>
  <div class="month-balance"><b> 円</b></div>
</div>
<div class="budget odd-color">
  <div class="category-budget fas fa-faucet"> 水道代</div>
  <div class="month-budget"><b> 円</b></div>
  <div class="month-expense"><%= @fixed_cost.where(fixed_cost_category_id: 6).sum(:price).to_s(:delimited)%><b> 円</b></div>
  <div class="month-balance"><b> 円</b></div>
</div>
<div class="budget even-color">
  <div class="category-budget fas fa-school"> 教育費</div>
  <div class="month-budget"><b> 円</b></div>
  <div class="month-expense"><%= @fixed_cost.where(fixed_cost_category_id: 7).sum(:price).to_s(:delimited)%><b> 円</b></div>
  <div class="month-balance"><b> 円</b></div>
</div>
<div class="budget odd-color">
  <div class="category-budget fas fa-notes-medical"> 保険代</div>
  <div class="month-budget"><b> 円</b></div>
  <div class="month-expense"><%= @fixed_cost.where(fixed_cost_category_id: 8).sum(:price).to_s(:delimited)%><b> 円</b></div>
  <div class="month-balance"><b> 円</b></div>
</div>
<div class="budget even-color">
  <div class="category-budget fas fa-coins"> ローン</div>
  <div class="month-budget"><b> 円</b></div>
  <div class="month-expense"><%= @fixed_cost.where(fixed_cost_category_id: 9).sum(:price).to_s(:delimited)%><b> 円</b></div>
  <div class="month-balance"><b> 円</b></div>
</div>
<div class="budget odd-color">
  <div class="category-budget fas fa-question-circle"> その他</div>
  <div class="month-budget"><b> 円</b></div>
  <div class="month-expense"><%= @fixed_cost.where(fixed_cost_category_id: 10).sum(:price).to_s(:delimited)%><b> 円</b></div>
  <div class="month-balance"><b> 円</b></div>
</div>
<div class="budget-bar">
</div>
<div class="budget orange-color">
  <div class="category-budget fas fa-money-bill-wave-alt"> 変動費</div>
  <div class="month-budget"><b> 円</b></div>
  <div class="month-expense"><%= @variable_cost_month.to_s(:delimited)%><b> 円</b></div>
  <div class="month-balance"><b> 円</b></div>
</div>
<div class="budget odd-color">
  <div class="category-budget fas fa-utensils"> 食費</div>
  <div class="month-budget"><b> 円</b></div>
  <div class="month-expense"><%= @variable_cost.where(variable_cost_category_id: 2).sum(:price).to_s(:delimited)%><b> 円</b></div>
  <div class="month-balance"><b> 円</b></div>
</div>
<div class="budget even-color">
  <div class="category-budget fas fa-box-tissue"> 日用品</div>
  <div class="month-budget"><b> 円</b></div>
  <div class="month-expense"><%= @variable_cost.where(variable_cost_category_id: 3).sum(:price).to_s(:delimited)%><b> 円</b></div>
  <div class="month-balance"><b> 円</b></div>
</div>
<div class="budget odd-color">
  <div class="category-budget fas fa-bus"> 交通費</div>
  <div class="month-budget"><b> 円</b></div>
  <div class="month-expense"><%= @variable_cost.where(variable_cost_category_id: 4).sum(:price).to_s(:delimited)%><b> 円</b></div>
  <div class="month-balance"><b> 円</b></div>
</div>
<div class="budget even-color">
  <div class="category-budget fas fa-futbol"> 趣味・娯楽</div>
  <div class="month-budget"><b> 円</b></div>
  <div class="month-expense"><%= @variable_cost.where(variable_cost_category_id: 5).sum(:price).to_s(:delimited)%><b> 円</b></div>
  <div class="month-balance"><b> 円</b></div>
</div>
<div class="budget odd-color">
  <div class="category-budget fas fa-tshirt"> 衣服・美容</div>
  <div class="month-budget"><b> 円</b></div>
  <div class="month-expense"><%= @variable_cost.where(variable_cost_category_id: 6).sum(:price).to_s(:delimited)%><b> 円</b></div>
  <div class="month-balance"><b> 円</b></div>
</div>
<div class="budget even-color">
  <div class="category-budget fas fa-hospital-user"> 健康・医療</div>
  <div class="month-budget"><b> 円</b></div>
  <div class="month-expense"><%= @variable_cost.where(variable_cost_category_id: 7).sum(:price).to_s(:delimited)%><b> 円</b></div>
  <div class="month-balance"><b> 円</b></div>
</div>
<div class="budget odd-color">
  <div class="category-budget fas fa-book-reader"> 教養・教育</div>
  <div class="month-budget"><b> 円</b></div>
  <div class="month-expense"><%= @variable_cost.where(variable_cost_category_id: 8).sum(:price).to_s(:delimited)%><b> 円</b></div>
  <div class="month-balance"><b> 円</b></div>
</div>
<div class="budget even-color">
  <div class="category-budget fas fa-book-open"> 書籍</div>
  <div class="month-budget"><b> 円</b></div>
  <div class="month-expense"><%= @variable_cost.where(variable_cost_category_id: 9).sum(:price).to_s(:delimited)%><b> 円</b></div>
  <div class="month-balance"><b> 円</b></div>
</div>
<div class="budget odd-color">
  <div class="category-budget fas fa-coffee"> カフェ</div>
  <div class="month-budget"><b> 円</b></div>
  <div class="month-expense"><%= @variable_cost.where(variable_cost_category_id: 10).sum(:price).to_s(:delimited)%><b> 円</b></div>
  <div class="month-balance"><b> 円</b></div>
</div>
<div class="budget even-color">
  <div class="category-budget fas fa-user-friends"> 交際費</div>
  <div class="month-budget"><b> 円</b></div>
  <div class="month-expense"><%= @variable_cost.where(variable_cost_category_id: 11).sum(:price).to_s(:delimited)%><b> 円</b></div>
  <div class="month-balance"><b> 円</b></div>
</div>
<div class="budget odd-color">
  <div class="category-budget fas fa-gifts"> 特別費</div>
  <div class="month-budget"><b> 円</b></div>
  <div class="month-expense"><%= @variable_cost.where(variable_cost_category_id: 12).sum(:price).to_s(:delimited)%><b> 円</b></div>
  <div class="month-balance"><b> 円</b></div>
</div>
<div class="budget even-color">
  <div class="category-budget fas fa-question-circle"> その他</div>
  <div class="month-budget"><b> 円</b></div>
  <div class="month-expense"><%= @variable_cost.where(variable_cost_category_id: 13).sum(:price).to_s(:delimited)%><b> 円</b></div>
  <div class="month-balance"><b> 円</b></div>
</div>

app/views/budgets/edit.html.erb
<header class='top-page-header'>
  <%= render "shared/header" %>
  <% if user_signed_in? %>
    <div class="input-contents pc-menu">
      <ul class="inputs-lists">
        <li class="input-list" >
          <%= link_to ' HOME', root_path, class: "home_btn fas fa-home", id: "home-btn" %>
        </li>
        <li class="input-list">
          <%= link_to ' 収 入', new_income_path, class: "income_btn fas fa-money-bill", id: "income-btn" %>
        </li>
        <li class="input-list">
          <%= link_to ' 固定費', new_fixed_cost_path, class: "fixed_btn fas fa-money-bill-wave", id: "fixed-btn" %>
        </li>
        <li class="input-list">
          <%= link_to ' 変動費', new_variable_cost_path, class: "variable_btn fas fa-money-bill-wave-alt", id: "variable-btn" %>
        </li>
        <li class="input-list input-list-color" >
          <%= link_to ' 予 算', budgets_path, class: "budget_btn fas fa-wallet", id:"budget-btn" %>
        </li>
        <li class="input-list" >
          <%=  link_to ' 購入予定リスト', purchase_plans_path , class: "purchase_btn fas fa-shopping-cart ", id: "purchase-btn" %>
        </li>
      </ul>
    </div>
    <%= render "shared/sp_menu" %>
  <% end %>
</header>
<div class="set-contents">
  <div class="set-budget-title">
    予算編集
  </div>
  <div class="set-content">
    <%= form_with(model: @budget, url: budget_path(@budget), local: true) do |form| %>
      <%= render 'shared/budget_error_messages', model: form.object %>
      <div class="middle-set-content">
        <div class="set-left-content">
          <div class="set-title">
            固定費予算
          </div>
          <div class="budget-form">
            <label class="budget-category fas fa-house-user"> 住居費</label>
            <%= form.text_field :house, class: "budget-price" %><b>円</b>
          </div>
          <div class="budget-form">
            <label class="budget-category fas fa-broadcast-tower"> 通信費</label>
            <%= form.text_field :communications, class: "budget-price" %><b>円</b>
          </div>
          <div class="budget-form">
            <label class="budget-category fas fa-lightbulb"> 電気代</label>
            <%= form.text_field :electricity, class: "budget-price" %><b>円</b>
          </div>
          <div class="budget-form">
            <label class="budget-category fas fa-fire-alt"> ガス代</label>
            <%= form.text_field :gas, class: "budget-price" %><b>円</b>
          </div>
          <div class="budget-form">
            <label class="budget-category fas fa-faucet"> 水道代</label>
            <%= form.text_field :water, class: "budget-price" %><b>円</b>
          </div>
          <div class="budget-form">
            <label class="budget-category fas fa-school"> 教育費</label>
            <%= form.text_field :education, class: "budget-price" %><b>円</b>
          </div>
          <div class="budget-form">
            <label class="budget-category fas fa-notes-medical"> 保険代</label>
            <%= form.text_field :premium, class: "budget-price" %><b>円</b>
          </div>
          <div class="budget-form">
            <label class="budget-category fas fa-coins"> ローン</label>
            <%= form.text_field :lawn, class: "budget-price" %><b>円</b>
          </div>
          <div class="budget-form">
            <label class="budget-category fas fa-question-circle"> その他</label>
            <%= form.text_field :fixed_etcetera, class: "budget-price" %><b>円</b>
          </div>
        </div>
        <div class="set-right-content">
          <div class="set-title">
            変動費予算
          </div>
          <div class="budget-form">
            <label class="budget-category fas fa-utensils"> 食費</label>
            <%= form.text_field :food, class: "budget-price" %><b>円</b>
          </div>
          <div class="budget-form">
            <label class="budget-category fas fa-box-tissue"> 日用品</label>
            <%= form.text_field :commodity , class: "budget-price" %><b>円</b>
          </div>
          <div class="budget-form">
            <label class="budget-category fas fa-bus"> 交通費</label>
            <%= form.text_field :transportation, class: "budget-price" %><b>円</b>
          </div>
          <div class="budget-form">
            <label class="budget-category fas fa-futbol"> 趣味・娯楽</label>
            <%= form.text_field :hobby, class: "budget-price" %><b>円</b>
          </div>
          <div class="budget-form">
            <label class="budget-category fas fa-tshirt"> 衣服・美容</label>
            <%= form.text_field :clothes, class: "budget-price" %><b>円</b>
          </div>
          <div class="budget-form">
            <label class="budget-category fas fa-hospital-user"> 健康・医療</label>
            <%= form.text_field :health, class: "budget-price" %><b>円</b>
          </div>
          <div class="budget-form">
            <label class="budget-category fas fa-book-reader"> 教養・教育</label>
            <%= form.text_field :culture, class: "budget-price" %><b>円</b>
          </div>
          <div class="budget-form">
            <label class="budget-category fas fa-book-open"> 書籍</label>
            <%= form.text_field :book, class: "budget-price" %><b>円</b>
          </div>
          <div class="budget-form">
            <label class="budget-category fas fa-coffee"> カフェ</label>
            <%= form.text_field :cafe, class: "budget-price" %><b>円</b>
          </div>
          <div class="budget-form">
            <label class="budget-category fas fa-user-friends"> 交際費</label>
            <%= form.text_field :social, class: "budget-price" %><b>円</b>
          </div>
          <div class="budget-form">
            <label class="budget-category fas fa-gifts"> 特別費</label>
            <%= form.text_field :special, class: "budget-price" %><b>円</b>
          </div>
          <div class="budget-form">
            <label class="budget-category fas fa-question-circle"> その他</label>
            <%= form.text_field :variable_etcetera, class: "budget-price" %><b>円</b>
          </div>
        </div>
      </div>
      <div>
        <%= form.submit "保 存", class: "input-btn", id: "submit-btn" %>
      </div>
    <%end%>
  </div>
</div>
<%= render "shared/footer" %>

app/views/budgets/index.html.erb
<header class='top-page-header'>
  <%= render "shared/header" %>
  <% if user_signed_in? %>
    <div class="input-contents pc-menu">
      <ul class="inputs-lists">
        <li class="input-list" >
          <%= link_to ' HOME', root_path, class: "home_btn fas fa-home", id: "home-btn" %>
        </li>
        <li class="input-list">
          <%= link_to ' 収 入', new_income_path, class: "income_btn fas fa-money-bill", id: "income-btn" %>
        </li>
        <li class="input-list">
          <%= link_to ' 固定費', new_fixed_cost_path, class: "fixed_btn fas fa-money-bill-wave", id: "fixed-btn" %>
        </li>
        <li class="input-list">
          <%= link_to ' 変動費', new_variable_cost_path, class: "variable_btn fas fa-money-bill-wave-alt", id: "variable-btn" %>
        </li>
        <li class="input-list input-list-color" >
          <%= link_to ' 予 算', budgets_path, class: "budget_btn fas fa-wallet", id:"budget-btn" %>
        </li>
        <li class="input-list" >
          <%=  link_to ' 購入予定リスト', purchase_plans_path , class: "purchase_btn fas fa-shopping-cart ", id: "purchase-btn" %>
        </li>
      </ul>
    </div>
    <%= render "shared/sp_menu" %>
  <% end %>
</header>
<div class="budget-contents">
  <div class="top-budget-content">
    <div class="budget-btn-box">
      <% unless @budget.present?%>
        <%= link_to '予算登録', new_budget_path , class: "budget-btn", id: "budget-new-btn" %>
      <% else %>
        <%=  link_to '予算編集', edit_budget_path(@budget) , class: "budget-btn", id: "budget-new-btn" %>
      <% end %>
    </div>
  </div>
  <div class="bottom-budget-content", id="aaa">
    <div class="budget-content">
      <div class="budget gray-color">
        <div class="category-budget top-font">分 類</div>
        <div class="month-budget top-font"><%= Date.today.mon%>月の予算</div>
        <div class="month-expense top-font"><%= Date.today.mon%>月使った金額</div>
        <div class="month-balance top-font">残り使える金額</div>
      </div>
      <% if @budget.present?%>
        <%= render "entered" %>
      <% else %>
        <%= render "blank" %>
      <% end %>
    </div>
  </div>
</div>
<%= render "shared/footer" %>

app/views/budgets/new.html.erb
<header class='top-page-header'>
  <%= render "shared/header" %>
  <% if user_signed_in? %>
    <div class="input-contents pc-menu">
      <ul class="inputs-lists">
        <li class="input-list" >
          <%= link_to ' HOME', root_path, class: "home_btn fas fa-home", id: "home-btn" %>
        </li>
        <li class="input-list">
          <%= link_to ' 収 入', new_income_path, class: "income_btn fas fa-money-bill", id: "income-btn" %>
        </li>
        <li class="input-list">
          <%= link_to ' 固定費', new_fixed_cost_path, class: "fixed_btn fas fa-money-bill-wave", id: "fixed-btn" %>
        </li>
        <li class="input-list">
          <%= link_to ' 変動費', new_variable_cost_path, class: "variable_btn fas fa-money-bill-wave-alt", id: "variable-btn" %>
        </li>
        <li class="input-list input-list-color" >
          <%= link_to ' 予 算', budgets_path, class: "budget_btn fas fa-wallet", id:"budget-btn" %>
        </li>
        <li class="input-list" >
          <%=  link_to ' 購入予定リスト', purchase_plans_path , class: "purchase_btn fas fa-shopping-cart ", id: "purchase-btn" %>
        </li>
      </ul>
    </div>
    <%= render "shared/sp_menu" %>
  <% end %>
</header>
<div class="set-contents">
  <div class="set-budget-title">
    予算登録
  </div>
  <div class="set-content">
    <%= form_with(model: @budget, local: true) do |form| %>
      <%= render 'shared/budget_error_messages', model: form.object %>
      <div class="middle-set-content">
        <div class="left-set-content">
          <div class="set-title">
            固定費予算
          </div>
          <div class="budget-form">
            <label class="budget-category fas fa-house-user"> 住居費</label>
            <%= form.text_field :house, value: 0, class: "budget-price" %><b>円</b>
          </div>
          <div class="budget-form">
            <label class="budget-category fas fa-broadcast-tower"> 通信費</label>
            <%= form.text_field :communications, value: 0, class: "budget-price" %><b>円</b>
          </div>
          <div class="budget-form">
            <label class="budget-category fas fa-lightbulb"> 電気代</label>
            <%= form.text_field :electricity, value: 0, class: "budget-price" %><b>円</b>
          </div>
          <div class="budget-form">
            <label class="budget-category fas fa-fire-alt"> ガス代</label>
            <%= form.text_field :gas, value: 0, class: "budget-price" %><b>円</b>
          </div>
          <div class="budget-form">
            <label class="budget-category fas fa-faucet"> 水道代</label>
            <%= form.text_field :water, value: 0, class: "budget-price" %><b>円</b>
          </div>
          <div class="budget-form">
            <label class="budget-category fas fa-school"> 教育費</label>
            <%= form.text_field :education, value: 0, class: "budget-price" %><b>円</b>
          </div>
          <div class="budget-form">
            <label class="budget-category fas fa-notes-medical"> 保険代</label>
            <%= form.text_field :premium, value: 0, class: "budget-price" %><b>円</b>
          </div>
          <div class="budget-form">
            <label class="budget-category fas fa-coins"> ローン</label>
            <%= form.text_field :lawn, value: 0, class: "budget-price" %><b>円</b>
          </div>
          <div class="budget-form">
            <label class="budget-category fas fa-question-circle"> その他</label>
            <%= form.text_field :fixed_etcetera, value: 0, class: "budget-price" %><b>円</b>
          </div>
        </div>
        <div class="set-right-content">
          <div class="set-title">
            変動費予算
          </div>
          <div class="budget-form">
            <label class="budget-category fas fa-utensils"> 食費</label>
            <%= form.text_field :food, value: 0, class: "budget-price" %><b>円</b>
          </div>
          <div class="budget-form">
            <label class="budget-category fas fa-box-tissue"> 日用品</label>
            <%= form.text_field :commodity, value: 0, class: "budget-price" %><b>円</b>
          </div>
          <div class="budget-form">
            <label class="budget-category fas fa-bus"> 交通費</label>
            <%= form.text_field :transportation, value: 0, value: 0, class: "budget-price" %><b>円</b>
          </div>
          <div class="budget-form">
            <label class="budget-category fas fa-futbol"> 趣味・娯楽</label>
            <%= form.text_field :hobby, value: 0, class: "budget-price" %><b>円</b>
          </div>
          <div class="budget-form">
            <label class="budget-category fas fa-tshirt"> 衣服・美容</label>
            <%= form.text_field :clothes, value: 0, class: "budget-price" %><b>円</b>
          </div>
          <div class="budget-form">
            <label class="budget-category fas fa-hospital-user"> 健康・医療</label>
            <%= form.text_field :health, value: 0, class: "budget-price" %><b>円</b>
          </div>
          <div class="budget-form">
            <label class="budget-category fas fa-book-reader"> 教養・教育</label>
            <%= form.text_field :culture, value: 0, class: "budget-price" %><b>円</b>
          </div>
          <div class="budget-form">
            <label class="budget-category fas fa-book-open"> 書籍</label>
            <%= form.text_field :book, value: 0, class: "budget-price" %><b>円</b>
          </div>
          <div class="budget-form">
            <label class="budget-category fas fa-coffee"> カフェ</label>
            <%= form.text_field :cafe, value: 0, class: "budget-price" %><b>円</b>
          </div>
          <div class="budget-form">
            <label class="budget-category fas fa-user-friends"> 交際費</label>
            <%= form.text_field :social, value: 0, class: "budget-price" %><b>円</b>
          </div>
          <div class="budget-form">
            <label class="budget-category fas fa-gifts"> 特別費</label>
            <%= form.text_field :special, value: 0, class: "budget-price" %><b>円</b>
          </div>
          <div class="budget-form">
            <label class="budget-category fas fa-question-circle"> その他</label>
            <%= form.text_field :variable_etcetera, value: 0, class: "budget-price" %><b>円</b>
          </div>
        </div>
      </div>
      <div>
        <%= form.submit "保 存", class: "input-btn", id: "submit-btn" %>
      </div>
    <%end%>
  </div>
</div>

<%= render "shared/footer" %>