config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'tops#index'
  resources :incomes, only: [:new, :create, :destroy] do
    collection do
      get 'search'
    end
  end
  resources :fixed_costs, only: [:new, :create, :destroy] do
    collection do
      get 'search'
    end
  end
  resources :variable_costs, only: [:new, :create, :destroy]  do
    collection do
      get 'search'
    end
  end
  resources :purchase_plans, only: [:index, :new, :create, :destroy]
  resources :budgets, only: [:index, :new, :create, :edit, :update]
end

app/models/variable_cost.rb
class VariableCost < ApplicationRecord
  belongs_to :user
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :variable_cost_category

  with_options presence: true do
    validates :price, numericality: { only_integer: true, greater_than: 0, less_than: 10_000_001, message: 'は半角数字で 1円 以上  1,000,000 円 以内で入力してください' }
    validates :expense_date
  end

  # 収入区分の選択が「--」の時は保存できないようにする
  validates :variable_cost_category_id, numericality: { other_than: 1, message: 'を選択してください' }

  # 過去１年間の月ごとの変動費を算出
  def self.variable_cost_monthly
    one_year_period = (1.years.ago.beginning_of_month)..(Date.today.end_of_month)
    VariableCost.where(expense_date: one_year_period).group('YEAR(expense_date)').group('MONTH(expense_date)').sum(:price)
  end

  # 今月の変動費を算出
  def self.variable_cost_this_month
    this_month = Date.today.beginning_of_month..Date.today.end_of_month
    VariableCost.where(expense_date: this_month).sum(:price)
  end

  # 変動費の検索
  def self.search(search1, search2, search3)
    if search1 != '1' && search2.present? && search3.present?
      VariableCost.where(variable_cost_category_id: search1).where("YEAR(expense_date) = #{search2} AND MONTH(expense_date) = #{search3}")
    elsif search1 != '1' && search2.present?
      VariableCost.where(variable_cost_category_id: search1).where("YEAR(expense_date) = #{search2}")
    elsif search1 != '1' && search3.present?
      VariableCost.where(variable_cost_category_id: search1).where("MONTH(expense_date) = #{search3}")
    elsif search1 != '1'
      VariableCost.where(variable_cost_category_id: search1)
    elsif search2.present? && search3.present?
      VariableCost.where("YEAR(expense_date) = #{search2} AND MONTH(expense_date) = #{search3}")
    elsif search2.present?
      VariableCost.where("YEAR(expense_date) = #{search2}")
    elsif search3.present?
      VariableCost.where("MONTH(expense_date) = #{search3}")
    else
      VariableCost.all
    end
  end
end

app/controllers/variable_costs_controller.rb
class VariableCostsController < ApplicationController
  before_action :set_variable_costs, only: [:new, :create, :destroy]

  def new
    @variable_cost = VariableCost.new
  end

  def create
    variable_cost = VariableCost.create(variable_cost_category_id: params[:variable_cost_category_id], remarks: params[:remarks], price: params[:price], expense_date: params[:expense_date], user_id: current_user.id)
    if variable_cost.valid?
      # ActiveHashのidをnameに変換
      category = VariableCostCategory.find(params[:variable_cost_category_id])
      # 金額を3桁区切りに変換
      price = variable_cost.price.to_s(:delimited)
      # 日付を年月日表記に変換
      date = variable_cost.expense_date.strftime('%Y年%m月%d日')
      # variable_cost, category, dateをjson形式で送信
      render json: { variable_cost: variable_cost, category: category, price: price, date: date }
    end
  end

  def destroy
    @variable_cost = VariableCost.find(params[:id])
    if @variable_cost.destroy
      redirect_to '/variable_costs/new'
    else
      render 'new'
    end
  end

  def search
    user = User.find(current_user.id)
    @variable_costs = user.variable_costs.search(params[:variable_cost_category_id], params[:year], params[:month]).order('expense_date DESC')
  end

  private

  def set_variable_costs
    user = User.find(current_user.id)
    @variable_costs = user.variable_costs.order('expense_date DESC')
  end

  def variable_cost_params
    params.require(:variable_cost).permit(:variable_cost_category_id, :remarks, :price, :expense_date).merge(user_id: current_user.id)
  end
end

app/helpers/variable_costs_helper.rb
module VariableCostsHelper
end

app/views/variable_costs/new.html.erb
<header class='top-page-header'>
  <%= render "shared/header" %>
  <% if user_signed_in? %>
    <div class="input-contents pc-menu">
      <ul class="inputs-lists">
        <li class="input-list" >
          <%= link_to ' HOME', root_path, class: "home_btn fas fa-home", id: "home-btn" %>
        </li>
        <li class="input-list">
          <%= link_to ' 収 入', new_income_path, class: "income_btn fas fa-money-bill", id: "income-btn" %>
        </li>
        <li class="input-list">
          <%= link_to ' 固定費', new_fixed_cost_path, class: "fixed_btn fas fa-money-bill-wave", id: "fixed-btn" %>
        </li>
        <li class="input-list input-list-color">
          <%= link_to ' 変動費', new_variable_cost_path, class: "variable_btn fas fa-money-bill-wave-alt", id: "variable-btn" %>
        </li>
        <li class="input-list" >
          <%= link_to ' 予 算', budgets_path, class: "budget_btn fas fa-wallet", id:"budget-btn" %>
        </li>
        <li class="input-list" >
          <%=  link_to ' 購入予定リスト', purchase_plans_path , class: "purchase_btn fas fa-shopping-cart ", id: "purchase-btn" %>
        </li>
      </ul>
    </div>
    <%= render "shared/sp_menu" %>
  <% end %>
</header>
<div class="input-box">
  <div class="input-forms">
    <%= form_with url: "/variable_costs", method: :post, id: "form" do |form| %>
    <div class="input-form">
      <h2 class="input-title">変動費入力</h2>
      <div>
        <label class="form-text">分　類</label>
        <%= form.collection_select(:variable_cost_category_id, VariableCostCategory.all, :id, :name, {}, {class: "input-select-btn", id: "category-id"}) %>
        <span class="indispensable">必須</span>
      </div>
      <div>
        <label class="form-text">備　考</label>
        <%= form.text_field :remarks, placeholder: "例：飲み会代", class: "input-remarks", id: "remarks" %>
        <span class="indispensable-none">　　</span>
      </div>
      <div>
        <label class="form-text">金　額</label>
        <%= form.text_field :price, placeholder: "半角数字 例：10000", class: "input-price", id: "price" %>
        <label class="form-text"></label>
        <span class="indispensable">必須</span>
      </div>
      <div>
        <label class="form-text">出金日</label>
        <%= form.date_field :expense_date, placeholder: "入金日", class: "input-date", id: "date" %>
        <span class="indispensable">必須</span>
      </div>
      <div>
          <%= form.submit "入 力", class: "input-btn", id: "submit-btn" %>
      </div>
    </div>
    <% end %>
  </div>
</div>
<div class="detail-box">
  <div class="detail-title-box">
    <h2 class="detail-title">変動費詳細</h2>
  </div>
  <div class="search-box">
    <%= form_with(url: search_variable_costs_path, local: true, method: :get, class: "search-form fas fa-search") do |form| %>
      <label class="form-text">分類:</label>
      <%= form.collection_select(:variable_cost_category_id, VariableCostCategory.all, :id, :name, {}, {class: "search-select"}) %>
      <label class="form-text">　出金日:</label>
      <%= form.select :year,(Date.today.year-10)..(Date.today.year+5), prompt:"--", class: "search-year" %>
      <label class="form-text">年 </label>
      <%= form.select :month, 1..12, prompt:"--", class: "search-month" %>
      <label class="form-text">月 </label>
      <%= form.submit "検索", class: "search-btn" %>
    <% end %>
  </div>
  <div class="details", id="details">
    <div class="detail">
      <div class="category-detail gray-color">
        分 類
      </div>
      <div class="price-detail gray-color">
        金 額
      </div>
      <div class="date-detail gray-color">
        出金日
      </div>
      <div class="remarks-detail gray-color">      
        備 考
      </div>
      <div class="delete-detail gray-color">
        削 除
      </div>
    </div>
    <div id="new-detail"></div>
    <% @variable_costs.each do |variable_cost| %>
    <div class="detail">
      <div class="category-detail white-color">
        <%= variable_cost.variable_cost_category.name %> 
      </div>
      <div class="price-detail expense-color white-color">
        <%= variable_cost.price.to_s(:delimited) %>円
      </div>
      <div class="date-detail white-color">
        <%= variable_cost.expense_date.strftime("%Y年%m月%d日") %>
      </div>
      <div class="remarks-detail white-color">
        <%= variable_cost.remarks %>
      </div>
      <div class="delete-detail white-color">
        <%= link_to '削除', variable_cost_path(variable_cost), method: :delete, class: "delete-input-btn", id: "submit-btn" %>
      </div>
    </div>
    <% end %>
  </div>
</div>
<%= render "shared/footer" %>

app/views/variable_costs/search.html.erb
<header class='top-page-header'>
  <%= render "shared/header" %>
  <% if user_signed_in? %>
    <div class="input-contents pc-menu">
      <ul class="inputs-lists">
        <li class="input-list" >
          <%= link_to ' HOME', root_path, class: "home_btn fas fa-home", id: "home-btn" %>
        </li>
        <li class="input-list ">
          <%= link_to ' 収 入', new_income_path, class: "income_btn fas fa-money-bill", id: "income-btn" %>
        </li>
        <li class="input-list">
          <%= link_to ' 固定費', new_fixed_cost_path, class: "fixed_btn fas fa-money-bill-wave", id: "fixed-btn" %>
        </li>
        <li class="input-list input-list-color">
          <%= link_to ' 変動費', new_variable_cost_path, class: "variable_btn fas fa-money-bill-wave-alt", id: "variable-btn" %>
        </li>
        <li class="input-list">
          <%= link_to ' 予 算', budgets_path, class: "budget_btn fas fa-wallet", id:"budget-btn" %>
        </li>
        <li class="input-list" >
          <%=  link_to ' 購入予定リスト', purchase_plans_path , class: "purchase_btn fas fa-shopping-cart ", id: "purchase-btn" %>
        </li>
      </ul>
    </div>
    <%= render "shared/sp_menu" %>
  <% end %>
</header>
<div class="search-result-content">
  <div class="search-result-title-box">
    <h2 class="search-result-title">変動費詳細検索結果</h2>
  </div>
  <div class="detail-box">
    <div class="details", id="details">
      <div class="detail">
        <div class="category-detail gray-color">
          分 類
        </div>
        <div class="price-detail gray-color">
          金 額
        </div>
        <div class="date-detail gray-color">
          出金日
        </div>
        <div class="remarks-detail gray-color">
          備 考
        </div>
        <div class="delete-detail gray-color">
          削 除
        </div>
      </div>
      <% @variable_costs.each do |variable_cost| %>
        <div class="detail">
          <div class="category-detail white-color">
            <%= variable_cost.variable_cost_category.name %> 
          </div>
          <div class="price-detail variable_cost-color white-color">
            <%= variable_cost.price.to_s(:delimited) %>円
          </div>
          <div class="date-detail white-color">
            <%= variable_cost.expense_date.strftime("%Y年%m月%d日") %>
          </div>
          <div class="remarks-detail white-color">      
            <%= variable_cost.remarks %>
          </div>
          <div class="delete-detail white-color">
            <%= link_to '削除', variable_cost_path(variable_cost.id), method: :delete, class: "delete-input-btn"%>
          </div>
        </div>
      <% end %>
    </div>
  </div>
  <div class="back-btn-box">
    <%= link_to ' 戻る', new_variable_cost_path, class: "back-btn", id: "back-btn" %>
  </div>
</div>
<%= render "shared/footer" %>