config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'tops#index'
  resources :incomes, only: [:new, :create, :destroy] do
    collection do
      get 'search'
    end
  end
  resources :fixed_costs, only: [:new, :create, :destroy] do
    collection do
      get 'search'
    end
  end
  resources :variable_costs, only: [:new, :create, :destroy]  do
    collection do
      get 'search'
    end
  end
  resources :purchase_plans, only: [:index, :new, :create, :destroy]
  resources :budgets, only: [:index, :new, :create, :edit, :update]
end

app/models/income.rb
class Income < ApplicationRecord
  belongs_to :user
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :income_category

  with_options presence: true do
    validates :price, numericality: { only_integer: true, greater_than: 0, less_than: 10_000_001, message: 'は半角数字で 1円 以上  1,000,000 円 以内で入力してください' }
    validates :income_date
  end
  # 収入区分の選択が「--」の時は保存できないようにする
  validates :income_category_id, numericality: { other_than: 1, message: 'を選択してください' }

  def self.income_monthly
    one_year_period = (1.years.ago.beginning_of_month)..(Date.today.end_of_month)
    Income.where(income_date: one_year_period).group('YEAR(income_date)').group('MONTH(income_date)').sum(:price)
  end

  def self.income_this_month
    this_month = Date.today.beginning_of_month..Date.today.end_of_month
    Income.where(income_date: this_month).sum(:price)
  end

  def self.search(search1, search2, search3)
    if search1 != '1' && search2.present? && search3.present?
      Income.where(income_category_id: search1).where("YEAR(income_date) = #{search2} AND MONTH(income_date) = #{search3}")
    elsif search1 != '1' && search2.present?
      Income.where(income_category_id: search1).where("YEAR(income_date) = #{search2}")
    elsif search1 != '1' && search3.present?
      Income.where(income_category_id: search1).where("MONTH(income_date) = #{search3}")
    elsif search1 != '1'
      Income.where(income_category_id: search1)
    elsif search2.present? && search3.present?
      Income.where("YEAR(income_date) = #{search2} AND MONTH(income_date) = #{search3}")
    elsif search2.present?
      Income.where("YEAR(income_date) = #{search2}")
    elsif search3.present?
      Income.where("MONTH(income_date) = #{search3}")
    else
      Income.all
    end
  end
end

app/controllers/incomes_controller.rb
class IncomesController < ApplicationController
  before_action :set_incomes, only: [:new, :create, :destroy]

  def new
    @income = Income.new
  end

  def create
    income = Income.create(income_category_id: params[:income_category_id], remarks: params[:remarks], price: params[:price], income_date: params[:income_date], user_id: current_user.id)
    if income.valid?
      # ActiveHashのidをnameに変換
      category = IncomeCategory.find(params[:income_category_id])
      # 金額を3桁区切りに変換
      price = income.price.to_s(:delimited)
      # 日付を年月日表記に変換
      date = income.income_date.strftime('%Y年%m月%d日')
      # income, category, dateをjson形式で送信
      render json: { income: income, category: category, price: price, date: date }
    end
  end

  def destroy
    @income = Income.find(params[:id])
    if @income.destroy
      redirect_to '/incomes/new'
    else
      render 'new'
    end
  end

  def search
    user = User.find(current_user.id)
    @incomes = user.incomes.search(params[:income_category_id], params[:year], params[:month]).order('income_date DESC')
  end

  private

  def set_incomes
    user = User.find(current_user.id)
    @incomes = user.incomes.order('income_date DESC')
  end

  def income_params
    params.require(:income).permit(:income_category_id, :remarks, :price, :income_date).merge(user_id: current_user.id)
  end
end

app/helpers/incomes_helper.rb
module IncomesHelper
end

app/views/incomes/new.html.erb
<header class='top-page-header'>
  <%= render "shared/header" %>
  <% if user_signed_in? %>
    <div class="input-contents pc-menu">
      <ul class="inputs-lists">
        <li class="input-list" >
          <%= link_to ' HOME', root_path, class: "home_btn fas fa-home", id: "home-btn" %>
        </li>
        <li class="input-list input-list-color">
          <%= link_to ' 収 入', new_income_path, class: "income_btn fas fa-money-bill", id: "income-btn" %>
        </li>
        <li class="input-list">
          <%= link_to ' 固定費', new_fixed_cost_path, class: "fixed_btn fas fa-money-bill-wave", id: "fixed-btn" %>
        </li>
        <li class="input-list">
          <%= link_to ' 変動費', new_variable_cost_path, class: "variable_btn fas fa-money-bill-wave-alt", id: "variable-btn" %>
        </li>
        <li class="input-list" >
          <%= link_to ' 予 算', budgets_path, class: "budget_btn fas fa-wallet", id:"budget-btn" %>
        </li>
        <li class="input-list" >
          <%=  link_to ' 購入予定リスト', purchase_plans_path , class: "purchase_btn fas fa-shopping-cart ", id: "purchase-btn" %>
        </li>
      </ul>
    </div>
    <%= render "shared/sp_menu" %>
  <% end %>
</header>
<div class="input-box">
  <div class="input-forms">
    <%= form_with url: "/incomes", method: :post, id: "form" do |form| %>
    <div class="input-form">
      <h2 class="input-title">収入入力</h2>
      <div>
        <label class="form-text">分　類</label>
        <%= form.collection_select(:income_category_id, IncomeCategory.all, :id, :name, {}, {class: "input-select-btn", id: "category-id"}) %>
        <span class="indispensable">必須</span>
      </div>
      <div>
        <label class="form-text">備　考</label>
        <%= form.text_field :remarks, placeholder: "例：残業代含む", class: "input-remarks", id: "remarks" %>
        <span class="indispensable-none">　　</span>
      </div>
      <div>
        <label class="form-text">金　額</label>
        <%= form.text_field :price, placeholder: "例：10000", class: "input-price", id: "price" %>
        <label class="form-text"></label>
        <span class="indispensable">必須</span>
      </div>
      <div>
        <label class="form-text">入金日</label>
        <%= form.date_field :income_date, placeholder: "入金日", class: "input-date", id: "date" %>
        <span class="indispensable">必須</span>
      </div>
      <div>
          <%= form.submit "入 力", class: "input-btn", id: "submit-btn" %>
      </div>
    </div>
    <% end %>
  </div>
</div>
<div class="detail-box">
  <div class="detail-title-box">
    <h2 class="detail-title">収入詳細</h2>
  </div>
  <div class="search-box">
    <%= form_with(url: search_incomes_path, local: true, method: :get, class: "search-form fas fa-search") do |form| %>
      <label class="form-text">分類:</label>
      <%= form.collection_select(:income_category_id, IncomeCategory.all, :id, :name, {}, {class: "search-select"}) %>
      <label class="form-text">　入金日:</label>
      <%= form.select :year,(Date.today.year-10)..(Date.today.year+5), prompt:"--", class: "search-year" %>
      <label class="form-text">年 </label>
      <%= form.select :month, 1..12, prompt:"--", class: "search-month" %>
      <label class="form-text">月 </label>
      <%= form.submit "検索", class: "search-btn" %>
    <% end %>
  </div>
  <div class="details", id="details">
    <div class="detail">
      <div class="category-detail gray-color">
        分 類
      </div>
      <div class="price-detail gray-color">
        金 額
      </div>
      <div class="date-detail gray-color">
        入金日
      </div>
      <div class="remarks-detail gray-color">
        備 考
      </div>
      <div class="delete-detail gray-color">
        削 除
      </div>
    </div>
    <div id="new-detail"></div>
    <% @incomes.each do |income| %>
    <div class="detail">
      <div class="category-detail white-color">
        <%= income.income_category.name %> 
      </div>
      <div class="price-detail income-color white-color">
        <%= income.price.to_s(:delimited) %>円
      </div>
      <div class="date-detail white-color">
        <%= income.income_date.strftime("%Y年%m月%d日") %>
      </div>
      <div class="remarks-detail white-color">
        <%= income.remarks %>
      </div>
      <div class="delete-detail white-color">
        <%= link_to '削除', income_path(income), method: :delete, class: "delete-input-btn"%>
      </div>
    </div>
    <% end %>
  </div>
</div>
<%= render "shared/footer" %>

app/views/incomes/search.html.erb
<header class='top-page-header'>
  <%= render "shared/header" %>
  <% if user_signed_in? %>
    <div class="input-contents pc-menu">
      <ul class="inputs-lists">
        <li class="input-list" >
          <%= link_to ' HOME', root_path, class: "home_btn fas fa-home", id: "home-btn" %>
        </li>
        <li class="input-list input-list-color">
          <%= link_to ' 収 入', new_income_path, class: "income_btn fas fa-money-bill", id: "income-btn" %>
        </li>
        <li class="input-list">
          <%= link_to ' 固定費', new_fixed_cost_path, class: "fixed_btn fas fa-money-bill-wave", id: "fixed-btn" %>
        </li>
        <li class="input-list">
          <%= link_to ' 変動費', new_variable_cost_path, class: "variable_btn fas fa-money-bill-wave-alt", id: "variable-btn" %>
        </li>
        <li class="input-list">
          <%= link_to ' 予 算', budgets_path, class: "budget_btn fas fa-wallet", id:"budget-btn" %>
        </li>
        <li class="input-list" >
          <%=  link_to ' 購入予定リスト', purchase_plans_path , class: "purchase_btn fas fa-shopping-cart ", id: "purchase-btn" %>
        </li>
      </ul>
    </div>
    <%= render "shared/sp_menu" %>
  <% end %>
</header>
<div class="search-result-contents">
<div class="search-result-content">
  <div class="search-result-title-box">
    <h2 class="search-result-title">収入詳細検索結果</h2>
  </div>
  <div class="detail-box">
    <div class="details", id="details">
      <div class="detail">
        <div class="category-detail gray-color">
          分 類
        </div>
        <div class="price-detail gray-color">
          金 額
        </div>
        <div class="date-detail gray-color">
          入金日
        </div>
        <div class="remarks-detail gray-color">      
          備 考
        </div>
        <div class="delete-detail gray-color">
          削 除
        </div>
      </div>
      <% @incomes.each do |income| %>
        <div class="detail">
          <div class="category-detail white-color">
            <%= income.income_category.name %> 
          </div>
          <div class="price-detail income-color white-color">
            <%= income.price.to_s(:delimited) %>円
          </div>
          <div class="date-detail white-color">
            <%= income.income_date.strftime("%Y年%m月%d日") %>
          </div>
          <div class="remarks-detail white-color">      
            <%= income.remarks %>
          </div>
          <div class="delete-detail white-color">
            <%= link_to '削除', income_path(income.id), method: :delete, class: "delete-input-btn"%>
          </div>
        </div>
      <% end %>
    </div>
  </div>
  <div class="back-btn-box">
    <%= link_to ' 戻る', new_income_path, class: "back-btn", id: "back-btn" %>
  </div>
</div>
</div>
<%= render "shared/footer" %>